apiVersion: v1
kind: Service
metadata:
  namespace: sandbox
  name: myip
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: myip
  ports:
    - protocol: TCP
      port: 8080
      targetPort: tcp8080
