apiVersion: v1
kind: Service
metadata:
  namespace: sandbox
  name: myip
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: myip
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
