apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myip
  namespace: sandbox
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: myip
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myip
    spec:
      containers:
      - image: service/myip:latest
        imagePullPolicy: Never
        name: myip
        ports:
        - containerPort: 8080
          name: tcp8080
        startupProbe:
          httpGet:
            path: /health
            port: tcp8080
          failureThreshold: 30
          periodSeconds: 2
        livenessProbe:
          httpGet:
            path: /health
            port: tcp8080
          failureThreshold: 1
          periodSeconds: 2
